#!/bin/bash

PWD=$(pwd)
TMP="$PWD/tmp"

if [ ! -d "$TMP/golang" ]; then
	mkdir -p "$TMP"
	git clone https://github.com/udhos/update-golang "$TMP/golang"
fi

cd "$TMP/golang" || return
git pull
sudo ./update-golang.sh
cd "$PWD" || return

go get -u github.com/golang/lint/golint
echo "Installed github.com/golang/lint/golint"
go get -u golang.org/x/tools/cmd/cover
echo "Installed golang.org/x/tools/cmd/cover"
go get -u golang.org/x/review/git-codereview
echo "Installed golang.org/x/review/git-codereview"
go get -u golang.org/x/tools/cmd/goimports
echo "Installed golang.org/x/tools/cmd/goimports"
go get -u golang.org/x/tools/cmd/gorename
echo "Installed golang.org/x/tools/cmd/gorename"
go get -u golang.org/x/tools/cmd/guru
echo "Installed golang.org/x/tools/cmd/guru"
go get -u github.com/cbednarski/hostess/cmd/hostess
echo "Installed github.com/cbednarski/hostess/cmd/hostess"
go get -u mvdan.cc/sh/cmd/shfmt
echo "Installed mvdan.cc/sh/cmd/shfmt"
