#!/bin/bash

sudo apt-get update && sudo apt-get install --no-install-recommends -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update && sudo apt-get install --no-install-recommends -y kubectl

mkdir -p "$HOME/.oh-my-zsh/plugins/zsh-kubectl-prompt"
git clone https://github.com/superbrothers/zsh-kubectl-prompt.git "$HOME/.oh-my-zsh/plugins/zsh-kubectl-prompt"