#!/bin/bash

if [ ! -d "$HOME/.vim" ]; then
	cd ~/ || return 1
	git clone --recursive https://github.com/jessfraz/.vim.git .vim
	ln -sf "$HOME/.vim/vimrc" "$HOME/.vimrc"
fi

cd "$HOME/.vim" || return 1
git pull
git submodule update --init
